version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graph
    ports: 
      - "8080:80"
    volumes:
      - ./app/html:/usr/share/nginx/html
